AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
