branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
env:
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"
jobs:
  include:
    - stage: test
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - chef-current-trusty
          packages:
            - chefdk
      services: docker
      before_script:
        - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
        - eval "$(chef shell-init bash)"
        - chef --version
        - cookstyle --version
        - foodcritic --version
    - stage: deploy
      deploy:
        provider: chef-supermarket
        client_key: newrelic.pem
        cookbook_category: Monitoring & Trending
        on:
          tags: true
        user_id: newrelic
        script: skip
        before_install:
        - openssl aes-256-cbc -K $encrypted_e7ed02806170_key -iv $encrypted_e7ed02806170_iv
          -in newrelic.pem.enc -out $HOME/newrelic.pem -d
matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

