addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
dist: trusty
env:
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - UNIT_AND_LINT=1
# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"
jobs:
  include:
    - stage: verify
      script: chef exec delivery local all
    - stage: acceptance
      env:
        - INSTANCE=default-centos-6
        - INSTANCE=default-centos-7
        - INSTANCE=default-ubuntu-1404
        - INSTANCE=default-ubuntu-1604
      script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}
    - stage: deploy
      deploy:
        before_install:
          - openssl aes-256-cbc -K $encrypted_e7ed02806170_key -iv $encrypted_e7ed02806170_iv
            -in newrelic.pem.enc -out $HOME/newrelic.pem -d
        client_key: newrelic.pem
        cookbook_category: Monitoring & Trending
        env:
          - UNIT_AND_LINT=1
        provider: chef-supermarket
        on:
          tags: true
        script: skip
        user_id: newrelic
services: docker
sudo: required
